name: flutter_radio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter  

  flutter_icons:
    git: https://github.com/jibiel/flutter-icons

  flutter_riverpod: ^2.6.1
  go_router: ^14.6.2
  intl: ^0.19.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.3.3
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  retrofit: ^4.4.1
  dio: ^5.7.0
  cached_network_image: ^3.4.1
  search_choices: ^2.2.11
  realm: ^20.0.0
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  custom_lint: ^0.6.4
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  freezed: ^2.5.2
  retrofit_generator: ^8.2.1

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
